### ISSUE TITLE
Provider crashes when trying to create vulnerability policy

### ISSUE THREAD

**Issue by ericofusco** [PaloAltoNetworks/terraform-provider-prismacloudcompute#49]
## Describe the bug

Plugin crashed trying to create the resource `prismacloudcompute_ci_image_vulnerability_policy`.

## Expected behavior

Plugin not to crash.

## Current behavior

Plugin crashes with the following stack trace:

```
Stack trace from the terraform-provider-prismacloudcompute_v0.5.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 21 [running]:
github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/internal/convert.schemaToVulnerabilityImageExpiration(...)
	github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/internal/convert/vulnerability_image.go:97
github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/internal/convert.SchemaToVulnerabilityImageRules(0x7ad176)
	github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/internal/convert/vulnerability_image.go:81 +0x101f
github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/internal/provider.createPolicyVulnerabilityCiImage(0x0, {0xab2260, 0xc0002e0240})
	github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/internal/provider/resource_policies_vulnerability_ci_images.go:247 +0x65
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xaa9fe0, {0xc62a38, 0xc0004802c0}, 0x2, {0xab2260, 0xc0002e0240})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:318 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003b6ee0, {0xc62a38, 0xc0004802c0}, 0xc0004b6690, 0xc0004e4f40, {0xab2260, 0xc0002e0240})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:456 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000ae078, {0xc62a38, 0xc0004802c0}, 0xc00021e370)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000043620, {0xc62ae0, 0xc00009da10}, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xb3f280, 0xc000043620}, {0xc62ae0, 0xc00009da10}, 0xc0004ce060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022b180, {0xc6fd18, 0xc00037a000}, 0xc0000ac400, 0xc000293bf0, 0x10f5060, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00022b180, {0xc6fd18, 0xc00037a000}, 0xc0000ac400, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-prismacloudcompute_v0.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Steps to reproduce

1. Try to create the following `prismacloudcompute_ci_image_vulnerability_policy` resource.

```
resource "prismacloudcompute_ci_image_vulnerability_policy" "main" {
  rule {
    collections = [
      "Collection1",
    ]
    effect     = "alert"
    name       = "CI vulnerability policy 1"
    only_fixed = true

    alert_threshold {
      disabled = false
      value    = 1
    }

    block_threshold {
      enabled = true
      value   = 1
    }

    grace_days_policy {
      critical = 7
      high     = 30
      low      = 90
      medium   = 60
    }

    tag_rule {
      description = "Vulnerabilities tagged with exceptions"
      effect      = "ignore"
      name        = "Exception"
    }
  }
  rule {
    collections = [
      "Collection2",
    ]
    effect     = "alert"
    name       = "CI vulnerability policy 2"
    only_fixed = true

    alert_threshold {
      disabled = false
      value    = 1
    }

    block_threshold {
      enabled = true
      value   = 9
    }

    grace_days_policy {
      critical = 7
    }

    tag_rule {
      description = "Vulnerabilities tagged with exceptions"
      effect      = "ignore"
      name        = "Exception"
    }
  }
  rule {
    collections = [
      "All",
    ]
    effect     = "block"
    name       = "CI vulnerability policy 3"
    only_fixed = true

    alert_threshold {
      disabled = false
      value    = 4
    }

    block_threshold {
      enabled = false
      value   = 0
    }

    tag_rule {
      description = "Vulnerabilities tagged with exceptions"
      effect      = "ignore"
      name        = "Exception"
    }
  }
}
```

## Your Environment

- Version used: 0.5.0

**Comment by PANW-aharrell** [comment]
Fixed in 0.8.0 https://github.com/PaloAltoNetworks/terraform-provider-prismacloudcompute/pull/71
